<form action="/users" method="post">
    <div>
        <label>
            Nickname
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
    </div>
    <br>
    <div>
        <label>
            Email
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>