<a href="<?= $urls['allUsers'] ?>">Все пользователи</a>
<br>
<br>
<form action="/users" method="post">
    <div>
        <label>
            Nickname
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
        <?php if (isset($errors['nickname'])) : ?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif ?>
    </div>
    <br>
    <div>
        <label>
            Email
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <br>
    <input type="submit" value="Submit">
</form>